spring:
  application:
    name: order-service
    
server:
  port: 8202

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
turbine:
  app-config: order order-service, zuul
  cluster-name-expression: new String("default")